
// Authentication

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const LOAD_BOT_SUCCESS = "LOAD_BOT_SUCCESS";
export const LOAD_PERMISSIONS = "LOAD_PERMISSIONS";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

// Conversations

export const LOAD_CONVERSATION = "LOAD_CONVERSATION";
export const LOAD_CONVERSATION_SUCCESS = "LOAD_CONVERSATION_SUCCESS";
export const LOAD_CONVERSATION_FAIL = "LOAD_CONVERSATION_FAIL";
export const LOAD_VARIABLES = "LOAD_VARIABLES";
export const LOAD_VARIABLES_SUCCESS = "LOAD_VARIABLES_SUCCESS";
export const LOAD_VARIABLES_FAIL = "LOAD_VARIABLES_FAIL";

// Quests

export const LOAD_QUESTS = "LOAD_QUESTS";
export const LOAD_QUESTS_SUCCESS = "LOAD_QUESTS_SUCCESS";
export const LOAD_QUESTS_FAIL = "LOAD_QUESTS_FAIL";
export const SEND_QUEST = "SEND_QUEST";