# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swivl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '10.0'
  # Pods for Swivl
  pod 'UrbanAirship-iOS-SDK'

  target 'Swivl-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwivlTests' do
    inherit! :search_paths
    # Pods for testing
  end

end